version: "3.9"
services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_DB: "technique"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  web:
    build: ./web
    environment:
        - MYSQL_DATABASE=technique
        - MYSQL_ROOT_PASSWORD=password
        - PYTHONUNBUFFERED=1
    restart: always
    ports:
      - "5000:5000"